import { ModuleDefinition } from '../types';
import { ProduitRoot } from '../../../pages/stocks/ProduitRoot';
import { StocksPage } from '../../../pages/stocks/StocksPage';
import { ProductFormPage } from '../../../pages/stocks/ProductFormPage';
import { CategoriesPage } from '../../../pages/stocks/CategoriesPage';
import { FournisseursPage } from '../../../pages/stocks/FournisseursPage';
import { MouvementsPage } from '../../../pages/stocks/MouvementsPage';
import { InventaireHome } from '../../../pages/stocks/inventaire/InventaireHome';
import { SessionsInventairePage } from '../../../pages/stocks/inventaire/SessionsInventairePage';
import { ControleInventairePage } from '../../../pages/stocks/inventaire/ControleInventairePage';
import { RapportInventairePage } from '../../../pages/stocks/inventaire/RapportInventairePage';
import { PromotionsPage } from '../../../pages/stocks/PromotionsPage';
import { StockDashboard } from '../../../pages/stocks/StockDashboard';

export const MANAGEMENT_STOCKS: ModuleDefinition[] = [
  {
    id: 'management-stocks-dashboard',
    path: '/gestion/stocks/dashboard',
    label: 'Tableau de bord',
    icon: 'TrendingUp',
    description: "Vue d'ensemble des stocks",
    roles: ['admin', 'gestionnaire', 'magasinier'],
    order: 100,
    component: StockDashboard,
    isManagement: true,
    isSidebarItem: true,
    isBottomNav: false,
  },
  {
    id: 'management-stocks',
    path: '/gestion/stocks',
    label: 'Produits',
    icon: 'Package',
    description: 'Gestion des produits',
    roles: ['admin', 'gestionnaire', 'magasinier'],
    order: 101,
    component: ProduitRoot,
    isManagement: true,
    isSidebarItem: true,
  },
  {
    id: 'management-stocks-produits',
    path: '/gestion/stocks/produits',
    label: 'Liste des produits',
    icon: 'Package',
    description: 'Liste complète des produits',
    roles: ['admin', 'gestionnaire', 'magasinier'],
    order: 102,
    component: StocksPage,
    isManagement: true,
    isSidebarItem: false,
  },
  {
    id: 'management-stocks-produits-nouveau',
    path: '/gestion/stocks/produits/nouveau',
    label: 'Nouveau produit',
    icon: 'PackagePlus',
    description: 'Créer un nouveau produit',
    roles: ['admin', 'gestionnaire', 'magasinier'],
    order: 103,
    component: ProductFormPage,
    isManagement: true,
    isSidebarItem: false,
  },
  {
    id: 'management-stocks-produits-modifier',
    path: '/gestion/stocks/produits/:id',
    label: 'Modifier le produit',
    icon: 'PackageEdit',
    description: 'Modifier un produit existant',
    roles: ['admin', 'gestionnaire', 'magasinier'],
    order: 104,
    component: ProductFormPage,
    isManagement: true,
    isSidebarItem: false,
  },
  {
    id: 'management-stocks-categories',
    path: '/gestion/stocks/categories',
    label: 'Catégories',
    icon: 'FolderTree',
    description: 'Gestion des catégories',
    roles: ['admin', 'gestionnaire'],
    order: 105,
    component: CategoriesPage,
    isManagement: true,
    isSidebarItem: false,
  },
  {
    id: 'management-stocks-fournisseurs',
    path: '/gestion/stocks/fournisseurs',
    label: 'Fournisseurs',
    icon: 'Truck',
    description: 'Gestion des fournisseurs',
    roles: ['admin', 'gestionnaire'],
    order: 106,
    component: FournisseursPage,
    isManagement: true,
    isSidebarItem: false,
  },
  {
    id: 'management-stocks-mouvements',
    path: '/gestion/stocks/mouvements',
    label: 'Mouvements',
    icon: 'GitBranch',
    description: 'Historique des mouvements',
    roles: ['admin', 'gestionnaire', 'magasinier'],
    order: 107,
    component: MouvementsPage,
    isManagement: true,
    isSidebarItem: false,
  },
  // ============================================================
  // INVENTAIRE — Nouveaux modules avec InventaireHome
  // ============================================================
  {
    id: 'management-stocks-inventaire',
    path: '/gestion/stocks/inventaire',
    label: 'Inventaire',
    icon: 'ClipboardList',
    description: "Gestion des sessions d'inventaire",
    roles: ['admin', 'gestionnaire', 'magasinier'],
    order: 108,
    component: InventaireHome,
    isManagement: true,
    isSidebarItem: false,
    isBottomNav: false,
  },
  {
    id: 'management-stocks-inventaire-sessions',
    path: '/gestion/stocks/inventaire/sessions',
    label: 'Sessions',
    icon: 'ClipboardList',
    description: "Liste des sessions d'inventaire",
    roles: ['admin', 'gestionnaire', 'magasinier'],
    order: 108.1,
    component: SessionsInventairePage,
    isManagement: true,
    isSidebarItem: false,
    isBottomNav: false,
  },
  {
    id: 'management-stocks-inventaire-controle',
    path: '/gestion/stocks/inventaire/controle',
    label: 'Contrôle',
    icon: 'CheckSquare',
    description: "Comptage des produits",
    roles: ['admin', 'gestionnaire', 'magasinier'],
    order: 108.2,
    component: ControleInventairePage,
    isManagement: true,
    isSidebarItem: false,
    isBottomNav: false,
  },
  {
    id: 'management-stocks-inventaire-controle-detail',
    path: '/gestion/stocks/inventaire/controle/:id',
    label: 'Contrôle détail',
    icon: 'CheckSquare',
    description: "Comptage des produits",
    roles: ['admin', 'gestionnaire', 'magasinier'],
    order: 108.3,
    component: ControleInventairePage,
    isManagement: true,
    isSidebarItem: false,
    isBottomNav: false,
  },
  {
    id: 'management-stocks-inventaire-rapport',
    path: '/gestion/stocks/inventaire/rapport',
    label: 'Rapports',
    icon: 'BarChart',
    description: "Rapports d'inventaire",
    roles: ['admin', 'gestionnaire', 'magasinier'],
    order: 108.4,
    component: RapportInventairePage,
    isManagement: true,
    isSidebarItem: false,
    isBottomNav: false,
  },
  {
    id: 'management-stocks-inventaire-rapport-detail',
    path: '/gestion/stocks/inventaire/rapport/:id',
    label: 'Rapport détail',
    icon: 'BarChart',
    description: "Rapport d'inventaire détaillé",
    roles: ['admin', 'gestionnaire', 'magasinier'],
    order: 108.5,
    component: RapportInventairePage,
    isManagement: true,
    isSidebarItem: false,
    isBottomNav: false,
  },
  // ============================================================
  // PROMOTIONS
  // ============================================================
  {
    id: 'management-stocks-promotions',
    path: '/gestion/stocks/promotions',
    label: 'Promotions',
    icon: 'Tag',
    description: 'Gestion des promotions et tarifs',
    roles: ['admin', 'gestionnaire'],
    order: 109,
    component: PromotionsPage,
    isManagement: true,
    isSidebarItem: false,
  },
];
