// ============================================================
// DISPLAY LABELS — Noms lisibles pour composants & pages
// Version V3.1 — Sans doublons
// ============================================================

// ============================================================
// LABELS DES COMPOSANTS
// ============================================================
const COMPONENT_TYPE_LABELS: Record<string, string> = {
  box: 'Boîte',
  button: 'Bouton',
  card: 'Carte',
  text: 'Texte',
  input: 'Champ',
  select: 'Sélecteur',
  textarea: 'Zone de texte',
  checkbox: 'Case à cocher',
  radio: 'Bouton radio',
  badge: 'Étiquette',
  settings: 'Paramètre',
  upload: 'Téléversement',
  layout: 'Mise en page',
  nav: 'Navigation',
  sidebar: 'Menu latéral',
  breadcrumb: 'Fil d\'Ariane',
  notification: 'Notification',
  modal: 'Fenêtre',
  list: 'Liste',
  form: 'Formulaire',
  stat: 'Statistique',
  page: 'Page',
  image: 'Image',
  media: 'Média',
  loading: 'Chargement',
  client: 'Client',
  commande: 'Commande',
  divider: 'Séparateur',
  chip: 'Puce',
  tooltip: 'Info-bulle',
  popover: 'Pop-up',
  dropdown: 'Menu déroulant',
  tab: 'Onglet',
  accordion: 'Accordéon',
  stepper: 'Étapes',
  pagination: 'Pagination',
  tag: 'Étiquette',
  grid: 'Grille',
  icon: 'Icône',
  indicator: 'Indicateur',
  filters: 'Filtres',
  panel: 'Panneau',
  preview: 'Aperçu',
  state: 'État',
};

const COMPONENT_VARIANT_LABELS: Record<string, string> = {
  default: 'Standard',
  primary: 'Principal',
  secondary: 'Secondaire',
  success: 'Succès',
  danger: 'Danger',
  warning: 'Avertissement',
  info: 'Information',
  dark: 'Sombre',
  light: 'Clair',
  outlined: 'Contour',
  outline: 'Contour',
  shadow: 'Ombré',
  small: 'Petit',
  medium: 'Moyen',
  large: 'Grand',
  xlarge: 'Très grand',
  elevated: 'Surélevé',
  flat: 'Plat',
  glass: 'Verre',
  gradient: 'Dégradé',
  ghost: 'Transparent',
  icon: 'Icône',
  rounded: 'Arrondi',
  floating: 'Flottant',
  link: 'Lien',
  title: 'Titre',
  subtitle: 'Sous-titre',
  body: 'Corps',
  caption: 'Légende',
  label: 'Étiquette',
  stat: 'Valeur',
  heading1: 'Titre H1',
  heading2: 'Titre H2',
  heading3: 'Titre H3',
  heading4: 'Titre H4',
  muted: 'Discret',
  bold: 'Gras',
  italic: 'Italique',
  underline: 'Souligné',
  strikethrough: 'Barré',
  code: 'Code',
  pre: 'Préformaté',
  quote: 'Citation',
  filled: 'Rempli',
  search: 'Recherche',
  number: 'Numérique',
  password: 'Mot de passe',
  email: 'Email',
  tel: 'Téléphone',
  url: 'URL',
  date: 'Date',
  time: 'Heure',
  datetime: 'Date et heure',
  file: 'Fichier',
  range: 'Curseur',
  color: 'Couleur',
  multiple: 'Multiple',
  switch: 'Interrupteur',
  dot: 'Point',
  pill: 'Pilule',
  status: 'Statut',
  'button-primary': 'Bouton principal',
  'button-secondary': 'Bouton secondaire',
  field: 'Champ',
  section: 'Section',
  description: 'Description',
  group: 'Groupe',
  general: 'Général',
  avatar: 'Avatar',
  container: 'Conteneur',
  flex: 'Flexible',
  main: 'Principal',
  header: 'En-tête',
  footer: 'Pied',
  row: 'Ligne',
  col: 'Colonne',
  item: 'Élément',
  toast: 'Message temporaire',
  banner: 'Bannière',
  alert: 'Alerte',
  popup: 'Popup',
  inline: 'En ligne',
  fullscreen: 'Plein écran',
  confirmation: 'Confirmation',
  drawer: 'Tiroir',
  'bottom-sheet': 'Feuille inférieure',
  center: 'Centré',
  compact: 'Compact',
  table: 'Tableau',
  action: 'Action',
  error: 'Erreur',
  disabled: 'Désactivé',
  horizontal: 'Horizontal',
  vertical: 'Vertical',
  percentage: 'Pourcentage',
  trend: 'Tendance',
  up: 'Hausse',
  down: 'Baisse',
  neutral: 'Neutre',
  auth: 'Authentification',
  dashboard: 'Tableau de bord',
  management: 'Gestion',
  empty: 'Vide',
  maintenance: 'Maintenance',
  thumbnail: 'Vignette',
  cover: 'Couverture',
  contain: 'Contenu',
  circle: 'Circulaire',
  responsive: 'Adaptatif',
  video: 'Vidéo',
  audio: 'Audio',
  player: 'Lecteur',
  spinner: 'Roue',
  skeleton: 'Squelette',
  progress: 'Progression',
  screen: 'Écran',
  bar: 'Barre',
  dots: 'Points',
  pulse: 'Pulsation',
  'search-select': 'Recherche',
  'search-results': 'Résultats',
  'list-item': 'Élément de liste',
  detail: 'Détail',
  'status-badge': 'Statut',
  summary: 'Résumé',
  thick: 'Épais',
  selected: 'Sélectionné',
  closable: 'Fermable',
  top: 'Haut',
  bottom: 'Bas',
  left: 'Gauche',
  right: 'Droite',
  content: 'Contenu',
  step: 'Pas',
  active: 'Actif',
  available: 'Disponible',
  low: 'Stock bas',
  out: 'Rupture',
  conversation: 'Conversation',
  conversations: 'Conversations',
  dynamic: 'Dynamique',
};

export function getComponentLabel(componentKey: string): string {
  const [type, variant] = componentKey.split(':');
  const typeLabel = COMPONENT_TYPE_LABELS[type] || type;
  if (!variant) return typeLabel;
  const variantLabel = COMPONENT_VARIANT_LABELS[variant] || variant;
  return `${typeLabel} ${variantLabel.charAt(0).toLowerCase()}${variantLabel.slice(1)}`;
}

// ============================================================
// LABELS DES PAGES
// ============================================================
const PAGE_LABELS: Record<string, string> = {
  'Application': 'Application',
  'HomePage': 'Accueil',
  'DashboardRoot': 'Tableau de bord',
  'DashboardPage': 'Tableau de bord',
  'ManagementRoot': 'Gestion',
  'ManagementLayout': 'Mise en page gestion',
  'BoutiquePage': 'Boutique',
  'PanierPage': 'Panier',
  'BoutiqueCommandesPage': 'Commandes boutique',
  'BoutiqueServiceDetailPage': 'Détail service',
  'ServicesPage': 'Services',
  'ServicesAdminPage': 'Services (admin)',
  'ServiceFormPage': 'Fiche service',
  'ServicesServiceDetailPage': 'Détail service (admin)',
  'LoginPage': 'Connexion',
  'RegisterPage': 'Inscription',
  'ForgotPasswordPage': 'Mot de passe oublié',
  'ResetPasswordPage': 'Nouveau mot de passe',
  'MaintenancePage': 'Maintenance',
  'MessagesPage': 'Messagerie',
  'MessageDetail': 'Détail message',
  'MessageList': 'Liste messages',
  'MessageCompose': 'Nouveau message',
  'NotificationsPage': 'Notifications',
  'ClientsRoot': 'Clients',
  'ClientsPage': 'Liste clients',
  'ClientDetailPage': 'Fiche client',
  'ClientFormPage': 'Formulaire client',
  'ClientsRapportsPage': 'Rapports clients',
  'FidelitePage': 'Fidélité',
  'InteractionsPage': 'Interactions',
  'ClientCommandesPage': 'Mes commandes',
  'CommandesClientPage': 'Commandes clients',
  'CommandeClientDetailPage': 'Détail commande',
  'CommandeClientFormPage': 'Formulaire commande',
  'CommandeDetailPage': 'Détail commande',
  'CommandeFormPage': 'Formulaire commande',
  'NouvelleCommandePage': 'Nouvelle commande',
  'CaisseRoot': 'Caisse',
  'CaissePage': 'Caisse',
  'SessionsPage': 'Sessions',
  'SessionsCaissePage': 'Sessions caisse',
  'SessionDetailPage': 'Détail session',
  'VentesPage': 'Ventes',
  'VenteFormPage': 'Nouvelle vente',
  'CaisseRapportsPage': 'Rapports caisse',
  'NegociationPage': 'Négociation',
  'StocksPage': 'Stocks',
  'StockModulePage': 'Module stock',
  'StocksProductForm': 'Formulaire produit',
  'ProductFormPage': 'Fiche produit',
  'ProductFormModal': 'Créer un produit',
  'ProductDetailModal': 'Détail produit',
  'ProductFilters': 'Filtres produits',
  'StockIndicator': 'Indicateur stock',
  'StockDashboard': 'Tableau de bord stock',
  'ProduitRoot': 'Produits',
  'CategoriesPage': 'Catégories',
  'FournisseursPage': 'Fournisseurs',
  'MouvementsPage': 'Mouvements',
  'PertesPage': 'Pertes',
  'PromotionsPage': 'Promotions',
  'InventaireHome': 'Inventaire',
  'SessionsInventairePage': 'Sessions inventaire',
  'ControleInventairePage': 'Contrôle inventaire',
  'RapportInventairePage': 'Rapport inventaire',
  'ComptabiliteRoot': 'Comptabilité',
  'ComptabilitePage': 'Comptabilité',
  'JournalPage': 'Journal',
  'BilanPage': 'Bilan',
  'CompteResultatPage': 'Compte de résultat',
  'GrandLivrePage': 'Grand livre',
  'TvaPage': 'État de TVA',
  'TransactionsPage': 'Transactions',
  'PlanComptablePage': 'Plan comptable',
  'SaisieComptable': 'Saisie comptable',
  'FacturesPage': 'Factures',
  'FactureFormPage': 'Formulaire facture',
  'RappelsPage': 'Rappels',
  'ChargesPage': 'Charges',
  'ChargeFormPage': 'Formulaire charge',
  'ChargesUsuellesPage': 'Charges usuelles',
  'RHPage': 'RH',
  'EmployesPage': 'Employés',
  'EmployeFormPage': 'Fiche employé',
  'ContratsPage': 'Contrats',
  'CongesPage': 'Congés',
  'DemandesAbsencePage': 'Demandes d\'absence',
  'FichesPaiePage': 'Fiches de paie',
  'PointagesPage': 'Pointages',
  'EntrepotsPage': 'Entrepôts',
  'EntrepotFormPage': 'Formulaire entrepôt',
  'EntrepotDetailPage': 'Détail entrepôt',
  'EmplacementsPage': 'Emplacements',
  'MagasinsPage': 'Magasins',
  'MagasinFormPage': 'Formulaire magasin',
  'SettingsPage': 'Paramètres',
  'ThemeEditorPage': 'Éditeur de thème',
  'AnimationEditorPage': 'Éditeur d\'animations',
  'HomeEditorPage': 'Éditeur d\'accueil',
  'AnalyticsPage': 'Statistiques',
  'HistoriquePage': 'Historique',
  'DemandesPage': 'Demandes',
  'OfflineQueuePage': 'File hors ligne',
  'DebugPage': 'Debug',
};

export function getPageLabel(pageId: string): string {
  return PAGE_LABELS[pageId] || pageId;
}

// ============================================================
// LABELS DES ANIMATIONS
// ============================================================
const ANIMATION_LABELS: Record<string, string> = {
  none: 'Aucune',
  fadeIn: 'Apparition en fondu',
  fadeInUp: 'Apparition vers le haut',
  fadeInDown: 'Apparition vers le bas',
  fadeInLeft: 'Apparition depuis la gauche',
  fadeInRight: 'Apparition depuis la droite',
  slideInUp: 'Glissement vers le haut',
  slideInDown: 'Glissement vers le bas',
  slideInLeft: 'Glissement depuis la gauche',
  slideInRight: 'Glissement depuis la droite',
  zoomIn: 'Zoom avant',
  zoomInUp: 'Zoom avant depuis le bas',
  zoomInDown: 'Zoom avant depuis le haut',
  zoomInLeft: 'Zoom avant depuis la gauche',
  zoomInRight: 'Zoom avant depuis la droite',
  flipInX: 'Rotation horizontale',
  flipInY: 'Rotation verticale',
  rotateIn: 'Rotation',
  bounceIn: 'Rebond',
  elasticIn: 'Élastique',
  popIn: 'Apparition rapide',
  fadeScaleIn: 'Fondu avec zoom',
  fadeOut: 'Disparition en fondu',
  fadeOutUp: 'Disparition vers le haut',
  fadeOutDown: 'Disparition vers le bas',
  fadeOutLeft: 'Disparition vers la gauche',
  fadeOutRight: 'Disparition vers la droite',
  slideOutUp: 'Glissement vers le haut',
  slideOutDown: 'Glissement vers le bas',
  slideOutLeft: 'Glissement vers la gauche',
  slideOutRight: 'Glissement vers la droite',
  zoomOut: 'Zoom arrière',
  flipOutX: 'Rotation horizontale (sortie)',
  flipOutY: 'Rotation verticale (sortie)',
  rotateOut: 'Rotation (sortie)',
  bounceOut: 'Rebond (sortie)',
  popOut: 'Disparition rapide',
  scaleOut: 'Réduction',
  blurOut: 'Flou (sortie)',
  scaleTap: 'Réduction au clic',
  tapScale: 'Réduction au clic',
  tapBounce: 'Rebond au clic',
  liftHover: 'Élévation au survol',
  hoverLift: 'Élévation au survol',
  hoverElevate: 'Élévation avec ombre',
  hoverScale: 'Agrandissement au survol',
  hoverPulse: 'Pulsation au survol',
  hoverRotate: 'Rotation au survol',
  hoverBgGlow: 'Fond lumineux au survol',
  hoverBorderGlow: 'Bordure lumineuse au survol',
  glowHover: 'Effet lumineux au survol',
  focusRing: 'Anneau au focus',
  focusScale: 'Agrandissement au focus',
  focusGlow: 'Lueur au focus',
  dragElastic: 'Glissement élastique',
  inViewScale: 'Agrandissement à l\'apparition',
  inViewSlideUp: 'Glissement à l\'apparition',
  inViewFadeIn: 'Fondu à l\'apparition',
  listItemHover: 'Élément de liste au survol',
  listItemScale: 'Élément de liste qui grandit',
  gridItemHover: 'Élément de grille au survol',
  cardHover: 'Carte au survol',
  cardGlow: 'Carte lumineuse',
  pulse: 'Pulsation',
  shake: 'Secousse',
  wobble: 'Oscillation',
  jello: 'Gélatine',
  flash: 'Flash',
  rubberBand: 'Élastique',
  swing: 'Balancier',
  tada: 'Célébration',
  bounce: 'Rebond',
  heartBeat: 'Battement de cœur',
  staggerFadeIn: 'Apparition en cascade',
  staggerFadeUp: 'Cascade vers le haut',
  staggerFadeDown: 'Cascade vers le bas',
  staggerSlideUp: 'Cascade glissée vers le haut',
  staggerSlideDown: 'Cascade glissée vers le bas',
  staggerScale: 'Cascade zoom',
  staggerFlip: 'Cascade rotation',
  staggerRotate: 'Cascade rotation',
  staggerFadeRight: 'Cascade depuis la droite',
};

export function getAnimationLabel(animationId: string): string {
  return ANIMATION_LABELS[animationId] || animationId;
}
