/**
 * componentRegistry.ts – PARTIE 3/3
 * Helpers et exports
 */

import { COMPONENT_REGISTRY } from './componentRegistry_part1';
import { COMPONENT_CATEGORIES } from './componentRegistry_part2';

// ============================================================
// HELPERS
// ============================================================

export function getComponentCategories(): string[] {
  return Object.keys(COMPONENT_CATEGORIES);
}

export function getComponentsByCategory(category: string): string[] {
  return COMPONENT_CATEGORIES[category] || [];
}

export function getComponentLabel(component: string): string {
  const [type, variant] = component.split(':');
  const labels: Record<string, Record<string, string>> = {
    box: {
      default: 'Boîte standard',
      primary: 'Boîte primaire',
      secondary: 'Boîte secondaire',
      success: 'Boîte succès',
      danger: 'Boîte danger',
      warning: 'Boîte avertissement',
      info: 'Boîte information',
      dark: 'Boîte sombre',
      light: 'Boîte claire',
      outlined: 'Boîte avec bordure',
      shadow: 'Boîte avec ombre',
    },
    button: {
      primary: 'Bouton primaire',
      secondary: 'Bouton secondaire',
      success: 'Bouton succès',
      danger: 'Bouton danger',
      warning: 'Bouton avertissement',
      info: 'Bouton information',
      outline: 'Bouton contour',
      ghost: 'Bouton transparent',
      small: 'Bouton petit',
      large: 'Bouton grand',
      icon: 'Bouton icône',
      rounded: 'Bouton arrondi',
      floating: 'Bouton flottant',
      link: 'Bouton lien',
    },
    card: {
      default: 'Carte standard',
      small: 'Carte petite',
      medium: 'Carte moyenne',
      large: 'Carte grande',
      xlarge: 'Carte très grande',
      elevated: 'Carte surélevée',
      outlined: 'Carte avec bordure',
      flat: 'Carte plate',
      glass: 'Carte verre',
      gradient: 'Carte dégradé',
    },
    text: {
      title: 'Titre',
      subtitle: 'Sous-titre',
      body: 'Corps de texte',
      caption: 'Légende',
      label: 'Étiquette',
      stat: 'Valeur statistique',
      heading1: 'Titre H1',
      heading2: 'Titre H2',
      heading3: 'Titre H3',
      heading4: 'Titre H4',
      small: 'Texte petit',
      large: 'Texte grand',
      muted: 'Texte atténué',
      bold: 'Texte gras',
      italic: 'Texte italique',
      underline: 'Texte souligné',
      strikethrough: 'Texte barré',
      code: 'Code',
      pre: 'Préformaté',
      quote: 'Citation',
    },
    input: {
      default: 'Champ standard',
      filled: 'Champ rempli',
      outlined: 'Champ avec bordure',
      search: 'Champ de recherche',
      number: 'Champ numérique',
      password: 'Champ mot de passe',
      email: 'Champ email',
      tel: 'Champ téléphone',
      url: 'Champ URL',
      date: 'Champ date',
      time: 'Champ heure',
      datetime: 'Champ date/heure',
      file: 'Champ fichier',
      range: 'Curseur',
      color: 'Champ couleur',
    },
    select: {
      default: 'Sélecteur standard',
      filled: 'Sélecteur rempli',
      outlined: 'Sélecteur avec bordure',
      multiple: 'Sélecteur multiple',
    },
    textarea: {
      default: 'Zone de texte standard',
      filled: 'Zone de texte remplie',
      outlined: 'Zone de texte avec bordure',
    },
    checkbox: { default: 'Case à cocher', switch: 'Interrupteur' },
    radio: { default: 'Bouton radio', card: 'Carte radio' },
    badge: {
      primary: 'Badge primaire',
      secondary: 'Badge secondaire',
      success: 'Badge succès',
      danger: 'Badge danger',
      warning: 'Badge avertissement',
      info: 'Badge information',
      dark: 'Badge sombre',
      light: 'Badge clair',
      outline: 'Badge contour',
      dot: 'Badge point',
      pill: 'Badge pilule',
      status: 'Badge statut',
    },
    settings: {
      card: 'Carte paramètres',
      section: 'Section paramètres',
      field: 'Champ paramètres',
      'button-primary': 'Bouton paramètres primaire',
      'button-secondary': 'Bouton paramètres secondaire',
      checkbox: 'Case à cocher',
      radio: 'Bouton radio',
      label: 'Étiquette paramètres',
      description: 'Description',
      preview: 'Aperçu',
      switch: 'Interrupteur',
      group: 'Groupe paramètres',
      divider: 'Séparateur paramètres',
    },
    upload: {
      general: 'Téléchargement général',
      image: 'Téléchargement image',
      video: 'Téléchargement vidéo',
      audio: 'Téléchargement audio',
      document: 'Téléchargement document',
      avatar: 'Téléchargement avatar',
      multiple: 'Téléchargement multiple',
    },
    layout: {
      container: 'Conteneur',
      grid: 'Grille',
      flex: 'Flex',
      sidebar: 'Barre latérale',
      main: 'Contenu principal',
      header: 'En-tête',
      footer: 'Pied de page',
      row: 'Ligne',
      col: 'Colonne',
      section: 'Section',
      page: 'Page',
    },
    nav: {
      item: 'Élément de navigation',
      dropdown: 'Menu déroulant',
      link: 'Lien',
      button: 'Bouton de navigation',
      icon: 'Icône de navigation',
      label: 'Étiquette de navigation',
    },
    sidebar: {
      item: 'Élément de sidebar',
      section: 'Section sidebar',
      header: 'En-tête sidebar',
      footer: 'Pied sidebar',
    },
    breadcrumb: { item: 'Élément de fil d\'Ariane', separator: 'Séparateur de fil d\'Ariane' },
    notification: {
      toast: 'Toast',
      banner: 'Bannière',
      alert: 'Alerte',
      badge: 'Badge notification',
      popup: 'Popup',
      inline: 'Notification en ligne',
      success: 'Notification succès',
      error: 'Notification erreur',
      warning: 'Notification avertissement',
      info: 'Notification information',
    },
    modal: {
      default: 'Modale standard',
      small: 'Modale petite',
      large: 'Modale grande',
      fullscreen: 'Modale plein écran',
      confirmation: 'Modale confirmation',
      drawer: 'Tiroir',
      'bottom-sheet': 'Feuille inférieure',
      center: 'Modale centrée',
      alert: 'Modale alerte',
    },
    list: {
      default: 'Liste standard',
      compact: 'Liste compacte',
      table: 'Tableau',
      card: 'Liste cartes',
      grid: 'Liste grille',
      universal: 'Liste universelle',
      ordered: 'Liste ordonnée',
      unordered: 'Liste non ordonnée',
      description: 'Liste description',
      action: 'Liste action',
      divider: 'Liste avec séparateur',
    },
    form: {
      default: 'Formulaire standard',
      inline: 'Formulaire en ligne',
      group: 'Groupe de champs',
      actions: 'Actions formulaire',
      error: 'Erreur formulaire',
      success: 'Succès formulaire',
      loading: 'Chargement formulaire',
      disabled: 'Formulaire désactivé',
      horizontal: 'Formulaire horizontal',
      vertical: 'Formulaire vertical',
    },
    stat: {
      default: 'Statistique standard',
      card: 'Carte statistique',
      number: 'Nombre',
      percentage: 'Pourcentage',
      trend: 'Tendance',
      up: 'Tendance hausse',
      down: 'Tendance baisse',
      neutral: 'Tendance neutre',
    },
    page: {
      default: 'Page standard',
      auth: 'Page authentification',
      dashboard: 'Tableau de bord',
      management: 'Page gestion',
      error: 'Page erreur',
      empty: 'Page vide',
      loading: 'Page chargement',
      maintenance: 'Page maintenance',
    },
    image: {
      thumbnail: 'Vignette',
      avatar: 'Avatar',
      cover: 'Couverture',
      contain: 'Contenu',
      rounded: 'Image arrondie',
      circle: 'Image circulaire',
      responsive: 'Image responsive',
    },
    media: { video: 'Vidéo', audio: 'Audio', player: 'Lecteur' },
    loading: {
      spinner: 'Spinner',
      skeleton: 'Squelette',
      progress: 'Barre de progression',
      screen: 'Écran de chargement',
      bar: 'Barre de chargement',
      dots: 'Points de chargement',
      pulse: 'Pulsation',
    },
    client: {
      'search-select': 'Recherche client',
      'search-results': 'Résultats recherche client',
      card: 'Carte client',
      'list-item': 'Élément de liste client',
    },
    commande: {
      form: 'Formulaire commande',
      detail: 'Détail commande',
      list: 'Liste commandes',
      'status-badge': 'Badge statut commande',
      summary: 'Résumé commande',
    },
    divider: {
      default: 'Séparateur horizontal',
      vertical: 'Séparateur vertical',
      thick: 'Séparateur épais',
      light: 'Séparateur léger',
    },
    chip: {
      default: 'Chip standard',
      selected: 'Chip sélectionné',
      outline: 'Chip contour',
      closable: 'Chip fermable',
    },
    tooltip: {
      default: 'Info-bulle standard',
      top: 'Info-bulle haut',
      bottom: 'Info-bulle bas',
      left: 'Info-bulle gauche',
      right: 'Info-bulle droite',
    },
    popover: { default: 'Popover standard' },
    dropdown: { default: 'Menu déroulant' },
    tab: { default: 'Onglet standard', pill: 'Onglet pilule', underline: 'Onglet souligné' },
    accordion: {
      default: 'Accordéon standard',
      item: 'Élément accordéon',
      header: 'En-tête accordéon',
      content: 'Contenu accordéon',
    },
    stepper: { default: 'Étapes', item: 'Étape', step: 'Pas' },
    pagination: { default: 'Pagination', item: 'Élément pagination', active: 'Élément actif' },
    tag: {
      default: 'Tag standard',
      primary: 'Tag primaire',
      success: 'Tag succès',
      danger: 'Tag danger',
      warning: 'Tag avertissement',
      info: 'Tag information',
      closable: 'Tag fermable',
    },
  };
  return labels[type]?.[variant] || component;
}

// ============================================================
// EXPORTS
// ============================================================

export { COMPONENT_REGISTRY } from './componentRegistry_part1';
export { COMPONENT_CATEGORIES } from './componentRegistry_part2';

export default COMPONENT_REGISTRY;
