import { ModuleDefinition } from './modulesTypes';
import { RHPage } from '../pages/RHPage';
import { EmployesPage } from '../pages/EmployesPage';
import { EmployeFormPage } from '../pages/EmployeFormPage';
import { ContratsPage } from '../pages/ContratsPage';
import { CongesPage } from '../pages/CongesPage';
import { FichesPaiePage } from '../pages/FichesPaiePage';
import { PointagesPage } from '../pages/PointagesPage';
import { DemandesAbsencePage } from '../pages/DemandesAbsencePage';

export const MANAGEMENT_RH: ModuleDefinition[] = [
  {
    id: 'management-rh',
    path: '/gestion/rh',
    label: 'RH',
    icon: 'Users',
    description: 'Ressources humaines',
    roles: ['admin', 'gestionnaire', 'employe'],
    order: 112,
    component: RHPage,
    isManagement: true,
    isSidebarItem: true,
  },
  {
    id: 'rh-employes',
    path: '/gestion/rh/employes',
    label: 'Employés',
    icon: 'Users',
    description: 'Gestion des employés',
    roles: ['admin', 'gestionnaire'],
    order: 112.1,
    component: EmployesPage,
    isManagement: true,
    isSidebarItem: false,
  },
  {
    id: 'rh-employe-nouveau',
    path: '/gestion/rh/employes/nouveau',
    label: 'Nouvel employé',
    icon: 'UserPlus',
    description: 'Ajouter un employé',
    roles: ['admin', 'gestionnaire'],
    order: 112.2,
    component: EmployeFormPage,
    isManagement: true,
    isSidebarItem: false,
  },
  {
    id: 'rh-employe-modifier',
    path: '/gestion/rh/employes/:id',
    label: 'Modifier employé',
    icon: 'UserEdit',
    description: 'Modifier un employé',
    roles: ['admin', 'gestionnaire'],
    order: 112.3,
    component: EmployeFormPage,
    isManagement: true,
    isSidebarItem: false,
  },
  {
    id: 'rh-contrats',
    path: '/gestion/rh/contrats',
    label: 'Contrats',
    icon: 'FileText',
    description: 'Gestion des contrats',
    roles: ['admin', 'gestionnaire'],
    order: 112.4,
    component: ContratsPage,
    isManagement: true,
    isSidebarItem: false,
  },
  {
    id: 'rh-conges',
    path: '/gestion/rh/conges',
    label: 'Congés',
    icon: 'Calendar',
    description: 'Demandes de congés',
    roles: ['admin', 'gestionnaire'],
    order: 112.5,
    component: CongesPage,
    isManagement: true,
    isSidebarItem: false,
  },
  {
    id: 'rh-fiches-paie',
    path: '/gestion/rh/fiches-paie',
    label: 'Fiches de paie',
    icon: 'CreditCard',
    description: 'Génération des paies',
    roles: ['admin', 'gestionnaire'],
    order: 112.6,
    component: FichesPaiePage,
    isManagement: true,
    isSidebarItem: false,
  },
  {
    id: 'rh-pointages',
    path: '/gestion/rh/pointages',
    label: 'Pointages',
    icon: 'Clock',
    description: 'Suivi des présences',
    roles: ['admin', 'gestionnaire'],
    order: 112.7,
    component: PointagesPage,
    isManagement: true,
    isSidebarItem: false,
  },
  {
    id: 'rh-demandes-absence',
    path: '/gestion/rh/demandes-absence',
    label: 'Demandes d\'absence',
    icon: 'Clock',
    description: 'Gestion des congés et absences',
    roles: ['admin', 'gestionnaire'],
    order: 112.8,
    component: DemandesAbsencePage,
    isManagement: true,
    isSidebarItem: false,
  },
];
