import { ModuleDefinition } from './modulesTypes';
import { ComptabiliteRoot } from '../pages/ComptabiliteRoot';
import { JournalPage } from '../pages/JournalPage';
import { BilanPage } from '../pages/BilanPage';
import { CompteResultatPage } from '../pages/CompteResultatPage';
import { GrandLivrePage } from '../pages/GrandLivrePage';
import { TvaPage } from '../pages/TvaPage';
import { TransactionsPage } from '../pages/TransactionsPage';
import { PlanComptablePage } from '../pages/PlanComptablePage';
import { SaisiePage } from '../pages/SaisieComptable';
import { FacturesPage } from '../pages/FacturesPage';
import { FactureFormPage } from '../pages/FactureFormPage';
import { RappelsPage } from '../pages/RappelsPage';
import { ChargesPage } from '../pages/ChargesPage';
import { ChargeFormPage } from '../pages/ChargeFormPage';
import { SessionsCaissePage } from '../pages/SessionsCaissePage';
import { ChargesUsuellesPage } from '../pages/ChargesUsuellesPage';
import { ExercicesPage } from '../pages/ExercicesPage';

export const MANAGEMENT_COMPTABILITE: ModuleDefinition[] = [
  {
    id: 'management-comptabilite',
    path: '/gestion/comptabilite',
    label: 'Comptabilité',
    icon: 'Receipt',
    description: 'Gestion comptable',
    roles: ['admin', 'gestionnaire', 'comptable'],
    order: 111,
    component: ComptabiliteRoot,
    isManagement: true,
    isSidebarItem: true,
  },
  {
    id: 'compta-journal',
    path: '/gestion/comptabilite/journal',
    label: 'Journal',
    icon: 'BookOpen',
    description: 'Livre d\'or',
    roles: ['admin', 'gestionnaire', 'comptable'],
    order: 111.1,
    component: JournalPage,
    isManagement: true,
    isSidebarItem: false,
  },
  {
    id: 'compta-bilan',
    path: '/gestion/comptabilite/bilan',
    label: 'Bilan',
    icon: 'Scale',
    description: 'Situation patrimoniale',
    roles: ['admin', 'gestionnaire', 'comptable'],
    order: 111.2,
    component: BilanPage,
    isManagement: true,
    isSidebarItem: false,
  },
  {
    id: 'compta-compte-resultat',
    path: '/gestion/comptabilite/compte-resultat',
    label: 'Compte de résultat',
    icon: 'Receipt',
    description: 'Produits / Charges',
    roles: ['admin', 'gestionnaire', 'comptable'],
    order: 111.3,
    component: CompteResultatPage,
    isManagement: true,
    isSidebarItem: false,
  },
  {
    id: 'compta-transactions',
    path: '/gestion/comptabilite/transactions',
    label: 'Transactions',
    icon: 'List',
    description: 'Écritures comptables',
    roles: ['admin', 'gestionnaire', 'comptable'],
    order: 111.4,
    component: TransactionsPage,
    isManagement: true,
    isSidebarItem: false,
  },
  {
    id: 'compta-plan-comptable',
    path: '/gestion/comptabilite/plan-comptable',
    label: 'Plan comptable',
    icon: 'Database',
    description: 'Plan OHADA',
    roles: ['admin', 'gestionnaire', 'comptable'],
    order: 111.5,
    component: PlanComptablePage,
    isManagement: true,
    isSidebarItem: false,
  },
  {
    // Route manquante : useExercices/useCreateExercice/useCloturerExercice
    // existaient sans page/route pour les utiliser.
    id: 'compta-exercices',
    path: '/gestion/comptabilite/exercices',
    label: 'Exercices comptables',
    icon: 'Calendar',
    description: 'Créer et clôturer les exercices comptables',
    roles: ['admin', 'gestionnaire', 'comptable'],
    order: 111.55,
    component: ExercicesPage,
    isManagement: true,
    isSidebarItem: false,
  },
  {
    id: 'compta-saisie',
    path: '/gestion/comptabilite/saisie',
    label: 'Saisie simplifiée',
    icon: 'FileText',
    description: 'Saisie facile des factures et dépenses',
    roles: ['admin', 'gestionnaire', 'comptable'],
    order: 111.6,
    component: SaisiePage,
    isManagement: true,
    isSidebarItem: false,
  },
  {
    id: 'compta-factures',
    path: '/gestion/comptabilite/factures',
    label: 'Factures',
    icon: 'Receipt',
    description: 'Gestion des factures',
    roles: ['admin', 'gestionnaire', 'comptable'],
    order: 111.7,
    component: FacturesPage,
    isManagement: true,
    isSidebarItem: false,
  },
  {
    id: 'compta-facture-nouvelle',
    path: '/gestion/comptabilite/factures/nouvelle',
    label: 'Nouvelle facture',
    icon: 'PlusCircle',
    description: 'Émettre ou recevoir une facture',
    roles: ['admin', 'gestionnaire', 'comptable'],
    order: 111.8,
    component: FactureFormPage,
    isManagement: true,
    isSidebarItem: false,
  },
  {
    id: 'compta-facture-modifier',
    path: '/gestion/comptabilite/factures/:id',
    label: 'Modifier facture',
    icon: 'Edit',
    description: 'Modifier une facture',
    roles: ['admin', 'gestionnaire', 'comptable'],
    order: 111.9,
    component: FactureFormPage,
    isManagement: true,
    isSidebarItem: false,
  },
  {
    id: 'compta-rappels',
    path: '/gestion/comptabilite/rappels',
    label: 'Rappels de paiement',
    icon: 'Bell',
    description: 'Factures à régler avant le 26',
    roles: ['admin', 'gestionnaire', 'comptable'],
    order: 111.10,
    component: RappelsPage,
    isManagement: true,
    isSidebarItem: false,
  },
  {
    id: 'compta-charges',
    path: '/gestion/comptabilite/charges',
    label: 'Charges',
    icon: 'DollarSign',
    description: 'Dépenses, salaires, ajustements',
    roles: ['admin', 'gestionnaire', 'comptable'],
    order: 111.11,
    component: ChargesPage,
    isManagement: true,
    isSidebarItem: false,
  },
  {
    id: 'compta-charge-nouvelle',
    path: '/gestion/comptabilite/charges/nouvelle',
    label: 'Nouvelle charge',
    icon: 'PlusCircle',
    description: 'Enregistrer une charge',
    roles: ['admin', 'gestionnaire', 'comptable'],
    order: 111.12,
    component: ChargeFormPage,
    isManagement: true,
    isSidebarItem: false,
  },
  {
    // 🆕 Route manquante : ChargeFormPage gérait déjà le mode édition
    // (via useParams<{id}>) mais aucune route ne permettait d'y accéder.
    id: 'compta-charge-edition',
    path: '/gestion/comptabilite/charges/:id',
    label: 'Modifier une charge',
    icon: 'Edit',
    description: 'Modifier une charge existante',
    roles: ['admin', 'gestionnaire', 'comptable'],
    order: 111.13,
    component: ChargeFormPage,
    isManagement: true,
    isSidebarItem: false,
  },
  {
    id: 'compta-charges-usuelles',
    path: '/gestion/comptabilite/charges-usuelles',
    label: 'Charges usuelles',
    icon: 'Tag',
    description: 'Gérez les charges récurrentes',
    roles: ['admin', 'gestionnaire', 'comptable'],
    order: 111.13,
    component: ChargesUsuellesPage,
    isManagement: true,
    isSidebarItem: false,
  },
  {
    id: 'compta-sessions-caisse',
    path: '/gestion/comptabilite/sessions-caisse',
    label: 'Sessions de caisse',
    icon: 'Coins',
    description: 'Historique des sessions fermées et écarts',
    roles: ['admin', 'gestionnaire', 'comptable'],
    order: 111.14,
    component: SessionsCaissePage,
    isManagement: true,
    isSidebarItem: false,
  },
  {
    id: 'compta-grand-livre',
    path: '/gestion/comptabilite/grand-livre',
    label: 'Grand Livre',
    icon: 'BookOpen',
    description: 'Mouvements et solde par compte',
    roles: ['admin', 'gestionnaire', 'comptable'],
    order: 111.15,
    component: GrandLivrePage,
    isManagement: true,
    isSidebarItem: false,
  },
  {
    id: 'compta-tva',
    path: '/gestion/comptabilite/tva',
    label: 'État de TVA',
    icon: 'Receipt',
    description: 'TVA collectée - TVA déductible',
    roles: ['admin', 'gestionnaire', 'comptable'],
    order: 111.16,
    component: TvaPage,
    isManagement: true,
    isSidebarItem: false,
  },
];
